language: bash

sudo: required
service: docker

addons:
  apt:
    packages:
     - docker-ce

before_install:
  - shopt -s globstar
  - docker pull koalaman/shellcheck
  - docker pull stedolan/jq
  - docker pull hadolint/hadolint:v1.15.0

script:
 - docker run --rm -v $(pwd):/mnt koalaman/shellcheck **/*.sh
 - for addon_folder in $(pwd)/*/ ; do docker run --rm hadolint/hadolint:v1.15.0 < "${addon_folder}Dockerfile"; done
 - cat -- **/*.json | docker run --rm -v $(pwd):/mnt stedolan/jq '.'

matrix:
  fast_finish: true
